In [79]:
import numpy as np         # 引入相关库
def gram_schmidt(vectors):     # 施密特正交化
    basis = []
    for v in vectors:
        w = v - np.sum( np.dot(v,b)*b  for b in basis)
        if (w > 1e-10).any():  
            basis.append(w/np.linalg.norm(w))
    return np.array(basis)
test = np.array([[1.0,0.0,1.0,0.0], [1.0,1.0,1.0,1.0], [-1.0,2.0,0.0,1.0]])
print (gram_schmidt(test))    # 求得一组正交单位基

[[ 7.07106781e-01  0.00000000e+00  7.07106781e-01  0.00000000e+00]
 [ 1.57009246e-16  7.07106781e-01  1.57009246e-16  7.07106781e-01]
 [-5.00000000e-01  5.00000000e-01  5.00000000e-01 -5.00000000e-01]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.from_iter(generator)) or the python sum builtin instead.
  """


In [80]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


#计算均值,要求输入数据为numpy的矩阵格式，行表示样本数，列表示特征    
def meanX(data):
    return np.mean(data, axis=0) #axis=0表示按照列来求均值，如果输入list,则axis=1


#LDA算法实现

#计算类内离散度矩阵子项si
def compute_si(xi):
    n = xi.shape[0]
    ui = meanX(xi)
    si = 0
    for i in range(0, n):
        si = si + ( xi[i, :] - ui).T * (xi[i, :] - ui )      #中心化，便于计算
    return si

#计算类间离散度矩阵Sb
def compute_Sb(x1, x2):
    dataX=np.vstack((x1,x2))#合并样本   
    print( "dataX:", dataX)
    #计算均值
    u1=meanX(x1)
    u2=meanX(x2)    
    u=meanX(dataX) #所有样本的均值
    Sb = (u-u1).T * (u-u1) + (u-u2).T * (u-u2)
    return Sb
    
        
def LDA(x1, x2):
    #计算类内离散度矩阵Sw
    s1 = compute_si(x1)
    s2 = compute_si(x2)     
    #Sw=(n1*s1+n2*s2)/(n1+n2)
    Sw = s1 + s2
    
    #计算类间离散度矩阵Sb
    #Sb=(n1*(m-m1).T*(m-m1)+n2*(m-m2).T*(m-m2))/(n1+n2)
    Sb = compute_Sb(x1, x2)
    
    #求最大特征值对应的特征向量    
    eig_value, vec = np.linalg.eig(np.mat(Sw).I*Sb)    #特征值和特征向量
    index_vec = np.argsort(-eig_value)                 #对eig_value从大到小排序，返回索引
    eig_index = index_vec[:1]                          #取出最大的特征值的索引
    w = vec[:, eig_index]                              #取出最大的特征值对应的特征向量
    return w

In [81]:
def createDataSet():                           #构造数据集
    X1 = np.mat(np.random.random((8, 2)) * 5 + 15)  #类别A      8行2列矩阵
    X2 = np.mat(np.random.random((8, 2)) * 5 + 2)   #类别B
    return X1, X2  

x1, x2 = createDataSet()


In [75]:
w = LDA(x1, x2)
print( "w:",w)

dataX: [[18.06525081 15.16428971]
 [19.39375251 19.94516363]
 [16.06144062 16.2030215 ]
 [17.25971715 18.4329283 ]
 [18.44995985 19.91087781]
 [16.95849183 15.45861313]
 [16.92146135 17.59698212]
 [15.59819655 18.28755155]
 [ 5.18997053  6.68319172]
 [ 5.49265193  5.82822888]
 [ 3.04287214  4.43853254]
 [ 4.1025411   3.21702547]
 [ 5.5656267   5.16701669]
 [ 3.00462154  4.09602483]
 [ 2.61641588  2.4575906 ]
 [ 5.69606608  3.63914038]]
w: [[0.93722432]
 [0.34872707]]
